# 00_tensorflow_fundamentals.ipynb

In [1]:
import tensorflow as tf

print(tf.__version__)

2.6.0


## tensorflow : 데이터 전처리, 데이터 모델링, 모델 제공을 위한 오픈소스 머신 러닝 라이브러리



In [2]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
scalar.ndim

0

In [4]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
vector.ndim # ndim은 number of dimensions

1

## 일반적으로 tensorflow를 사용할 때 위에서처럼 직접 텐서를 만들지 않습니다. 
## Tensorflow에 내장된 모듈인 tf.io나 tf.data 가 데이터를 읽고 쓸 때 자동으로 데이터를
## 텐서로 변환한 다음 나중에 신경망 모델에 적용 및 처리합니다.

## scalar (스칼라)는 rank가 0인 tensor! 왜냐하면 ndim이 0이라서 그렇습니다.
## tensor는 dimension에 제한이 없다는 것이 중요합니다!

In [9]:
matrix = tf.constant(
    [
        [10, 7],
        [7, 10]
    ]
)
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [10]:
matrix.ndim

2

In [11]:
matrix2 = tf.constant(
    [
        [10., 7.],
        [7., 10.]
    ]
)
matrix2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float32)>

## tensorflow는 기본적으로 tensor를 생성할 때, 자료형 (Datatype)을 int32나 float32로 설정합니다.

In [13]:
another_matrix = tf.constant(
    [
        [10., 7.],
        [3., 2.],
        [8., 9.]
    ],
    dtype = tf.float16
)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
another_matrix.ndim

2

In [15]:
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [20]:
tensor.ndim  # 2행 3열짜리 행렬이 3개가 있다! 
# rank가 3인 tensor!

3

## 위에서 굳이 scalar, vector, matrix, tensor 등등으로 구분해서 표현을 했지만
## 기술적으로는 사실 위의 모든 것이 tensor입니다.

In [21]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [26]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [27]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [28]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## tf.constant()을 사용해야 할지... tf.Variable()을 사용해야 할지...
## 우리가 해결할 문제에 따라서 선택하면 되고, 
## 우리가 실제로 직접 tensor를 만들 경우는 없습니다. 
## 왜? tensorflow가 데이터를 불러오고, 모델링할 때 알아서 선택해 줍니다.

In [31]:
random_1 = tf.random.Generator.from_seed(42) # np.random.seed(42)와 비슷
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

In [32]:
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [33]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

In [36]:
random_3, random_4, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

## 왜 shuffle을 해야하는지...
## 딥러닝시 이미지가 15,000개가 있을 때, 처음에 10,000은 고양이
## 그리고, 이어서 나머지 5,000은 개!
## 이 순서대로 학습을 하게 된다면 신경망에 overfit을 유발시킬 수도 있습니다.

In [305]:
not_shuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5]
])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]])>

In [322]:
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]])>

In [226]:
tf.random.set_seed(42)

In [390]:
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]])>

In [436]:
# tf.random.set_seed(42)

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

![scalar-vector-matrix-tensor 비교](images/00-scalar-vector-matrix-tensor.png)

## (224, 224, 3, 32)
## 224, 224 (첫부분 2차원) : 픽셀 단위로 이미지의 높이 (height) 와 너비 (width)
## 3 : 이미지의 컬러 채널 (RGB, Red Green Blue)
## 32 : 배치 (Batch) 크기 -  1번에 신경망이 처리할 이미지의 갯수

In [89]:
tf.ones(shape = (3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [91]:
tf.zeros(shape = (3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [94]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32) # 24개
A = tf.constant(numpy_A, shape=[2, 4, 3]) # 24 = 2 * 4 * 3

numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])>)

In [95]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [96]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

## tensor의 정보 (shape, rank, size)를 얻는 과정 
## shape : tensor를 이루는 각각의 차원의 길이 (elements의 수)
## Rank : tensor를 이루는 차원의 갯수 (scalar는 0 / vector는 1 / matrix는 2 / tensor는 n (number) )
## Axis or Dimension : tensor의 특정 차원을 지칭
## size : tensor를 이루는 items (elements의 갯수)

In [101]:
print("모든 elements의 자료형은 ", rank_4_tensor.dtype)
print("차원의 갯수 (rank)는 ", rank_4_tensor.ndim)
print("텐서의 shape는 ", rank_4_tensor.shape)
print("텐서의 axis 0에 속하는 element들은 ", rank_4_tensor.shape[0])
print("텐서의 axis 1에 속하는 element들은 ", rank_4_tensor.shape[1])
print("텐서의 마지막 axis에 속하는 element들은 ", rank_4_tensor.shape[-1])
print("모든 element의 갯수 (2 * 3 * 4 * 5)는 ", tf.size(rank_4_tensor).numpy())
# numpy()를 사용한 이유는 tf.size가 결과를 tensor로 주기 때문에 이 tensor를 numpy array형태로 변환이 필요

모든 elements의 자료형은  <dtype: 'float32'>
차원의 갯수 (rank)는  4
텐서의 shape는  (2, 3, 4, 5)
텐서의 axis 0에 속하는 element들은  2
텐서의 axis 1에 속하는 element들은  3
텐서의 마지막 axis에 속하는 element들은  5
모든 element의 갯수 (2 * 3 * 4 * 5)는  <class 'numpy.int32'>


In [102]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [103]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [113]:
rank_2_tensor = tf.constant([
    [10, 7],
    [3, 4]
])

In [114]:
# 각 행의 마지막 elements를 출력
rank_2_tensor[:, -2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  3])>

In [115]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_2_tensor, rank_2_tensor.ndim, rank_3_tensor, rank_3_tensor.ndim
# 파이썬에서 ...는 기존에 존재하는 것은 모두 유지

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 2,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]])>,
 3)

In [116]:
tf.expand_dims(rank_2_tensor, axis = -1)
# axis = -1 / 마지막 차원이라는 뜻

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [117]:
tensor = tf.constant([
    [10, 7],
    [3, 4]
])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [118]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [119]:
tensor = tf.Variable([
    [10, 7],
    [3, 4]
])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [120]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [121]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [122]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [123]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [124]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [125]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [126]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [127]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [128]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

## TensorFlow에서는 matrix multiplication을 tf.matmul()로 처리합니다.
## 파이썬에서 @는 matrix multiplication을 의미하기도 합니다. @는 annotation을 의미하기도 합니다.
## 규칙 1 : 안에 있는 차원이 같아야 한다
## (3, 5) @ (3, 5) ==> 안 됨!
## (5, 3) @ (3, 5) ==> 잘 됨!
## (3, 5) @ (5, 3) ==> 잘 됨!

## 규칙 2: 연산의 결과 행렬은 외부 차원들로 이루어 진다
## (5, 3) @ (3, 5) => (5, 5)
## (3, 5) @ (5, 3) => (3, 3)

In [129]:
tensor = tf.constant([
    [10, 7],
    [3, 4]
])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [130]:
# (2, 2) @ (2, 2)
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [131]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [134]:
X = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

Y = tf.constant([
    [7, 8],
    [9, 10],
    [11, 12]
])
X, Y, X.ndim, Y.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>,
 2,
 2)

In [ ]:
# (3, 2) @ (3, 2) => 규칙 1 위반

X @ Y

In [ ]:
tf.matmul(X, Y)

## 위와 같은 경우를 해결하려면
## (3, 2) @ (3, 2)
## 1) X의 shape 변경 => (2, 3) @ (3, 2) => 결과 (2, 2)
## 2) Y의 shape 변경 => (3, 2) @ (2, 3) => 결과 (3, 3)

In [137]:
tf.reshape(X, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [139]:
tf.reshape(X, shape=(2, 3)) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [140]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [141]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [144]:
X, tf.reshape(X, shape=(2, 3)), tf.transpose(X)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>)

In [145]:
tf.reshape(X, shape=(2, 3)) @ Y, tf.transpose(X) @ Y

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]])>)

In [146]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [148]:
tf.matmul(a = X, b= Y, transpose_a = True, transpose_b = False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [149]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [437]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [438]:
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [440]:
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [441]:
Y.shape, tf.reshape(Y, (2, 3)), tf.transpose(Y)

(TensorShape([3, 2]),
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]])>)

## tf.reshape() : 주어진 tensor의 shape를 지정한 shape로 바꾸어 준다. 그 값이 나온 순서대로 (행에서 그리고 열) 값을 채운다. 
## tf.transpose() : 축을 바꾸어준다.

In [442]:
B = tf.constant([1.7, 7.4])

In [443]:
C = tf.constant([1, 7])

In [444]:
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7])>)

In [445]:
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [446]:
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

In [447]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [448]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [453]:
E = tf.constant(np.random.randint(low = 0, high = 100, size = 50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 6, 68, 91, 13, 26, 24, 71, 44, 46, 10, 50, 17, 63, 56, 92, 84, 79,
       96, 39,  8, 23, 72, 39, 42, 43, 65,  1, 54, 54, 70, 43, 94, 37, 78,
       20, 81, 93, 30, 79, 13,  0, 44, 95, 38, 25, 34, 25, 19,  4, 61])>

In [469]:
tf.math.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [470]:
tf.math.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=96>

In [471]:
tf.math.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=47>

In [472]:
tf.math.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2359>

In [479]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=28.44>

In [468]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=808.5>

In [476]:
tf.math.argmax(E) # max 값을 가진 위치를 알려준다

<tf.Tensor: shape=(), dtype=int64, numpy=17>

In [477]:
tf.math.argmin(E) # min 값을 가진 위치를 알려준다

<tf.Tensor: shape=(), dtype=int64, numpy=40>

## ["Red", "Green", "Blue"] : 우리가 보는 라벨
## [0.98, 0.01, 0.01] : softmax를 통해서 고를 예측 확률 argmax

In [480]:
F = tf.constant(np.random.random(50))
F

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([0.87554278, 0.40352593, 0.85596206, 0.98904959, 0.87281304,
       0.20646059, 0.61111544, 0.43039855, 0.07732076, 0.32968703,
       0.26296983, 0.33655549, 0.69321445, 0.25391615, 0.63570385,
       0.0016405 , 0.52555945, 0.64351851, 0.39608375, 0.37860857,
       0.87891623, 0.45032602, 0.10232663, 0.34121392, 0.76516572,
       0.90544878, 0.70998925, 0.4944193 , 0.70044257, 0.12357105,
       0.50832023, 0.80009119, 0.24349573, 0.13670037, 0.02172801,
       0.37661289, 0.58245278, 0.21921336, 0.84599379, 0.53664226,
       0.980166  , 0.62000601, 0.86424909, 0.2466399 , 0.41342146,
       0.7130985 , 0.83867675, 0.94069129, 0.72880424, 0.21400572])>

In [482]:
tf.reduce_max(F), tf.argmax(F)

(<tf.Tensor: shape=(), dtype=float64, numpy=0.989049586432909>,
 <tf.Tensor: shape=(), dtype=int64, numpy=3>)

In [483]:
tf.reduce_min(F), tf.argmin(F)

(<tf.Tensor: shape=(), dtype=float64, numpy=0.0016405033549572456>,
 <tf.Tensor: shape=(), dtype=int64, numpy=15>)

In [485]:
print(f"F의 최대값의 위치는 {tf.argmax(F).numpy()}")
print(f"F의 최대값은 {tf.reduce_max(F).numpy()}")

F의 최대값의 위치는 3
F의 최대값은 0.989049586432909


In [490]:
print(f"tf.argmax()의 값을 이용해서 찾은 F의 최대값는 {F[tf.argmax(F)].numpy()}")
print(f"tf.reduce_max의 값과 tf.argmax()를 통해서 찾은 값은 같을까? {F[tf.argmax(F)].numpy() == tf.reduce_max(F).numpy()}")

tf.argmax()의 값을 이용해서 찾은 F의 최대값는 0.989049586432909
tf.reduce_max의 값과 tf.argmax()를 통해서 찾은 값은 같을까? True


In [494]:
G = tf.constant(np.random.randint(0, 100, 50), shape = (1, 1, 1, 1, 50))
G, G.shape, G.ndim

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int32, numpy=
 array([[[[[13,  8, 40, 80, 83,  4, 11, 53, 68, 39, 91, 57, 90, 30, 15,
            54, 28, 58, 69, 70, 11, 88, 70, 64, 84, 45, 74, 87, 46, 28,
            13, 92, 55, 12, 23, 84, 46, 70, 25, 34, 37, 98, 72, 40, 73,
            47, 32, 90, 47, 77]]]]])>,
 TensorShape([1, 1, 1, 1, 50]),
 5)

In [496]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

# 차원의 크기가 1인 차원을 제거해주는 함수

(TensorShape([50]), 1)

In [498]:
some_list = [0, 1, 2, 3]
some_list

[0, 1, 2, 3]

In [502]:
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [503]:
tf.one_hot(some_list, depth=4, on_value="On", off_value="Off")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'On', b'Off', b'Off', b'Off'],
       [b'Off', b'On', b'Off', b'Off'],
       [b'Off', b'Off', b'On', b'Off'],
       [b'Off', b'Off', b'Off', b'On']], dtype=object)>

In [504]:
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [505]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [508]:
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [509]:
H.dtype

tf.int32

In [512]:
H = tf.cast(H, dtype=tf.float16)
H.dtype, H

(tf.float16,
 <tf.Tensor: shape=(9,), dtype=float16, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)>)

In [513]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [514]:
H = tf.cast(H, dtype=tf.float32)
H.dtype, H

(tf.float32,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>)

In [515]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [519]:
H = tf.cast(H, dtype=tf.int32)
H.dtype, H

(tf.int32,
 <tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>)

In [520]:
tf.math.log(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Log}}; Op<name=Log; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Log]

In [521]:
H = tf.cast(H, dtype=tf.float32)
H.dtype, H

(tf.float32,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>)

In [523]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [524]:
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [525]:
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [526]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [527]:
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 13, 60])>

In [528]:
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 13, 60])>

In [533]:
# NumPy array를 통해서 tensor를 생성
J = tf.constant(np.array([3., 7., 10.]))
J, type(J), J.numpy()

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>,
 tensorflow.python.framework.ops.EagerTensor,
 array([ 3.,  7., 10.]))

In [531]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [534]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [535]:
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
numpy_J, tensor_J

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 3.,  7., 10.], dtype=float32)>)

In [536]:
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [542]:
def function(x, y):
    return x ** 2 + y

In [543]:
x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [544]:
@tf.function # decorator
def tf_function(x, y):
    return x ** 2 + y

In [545]:
tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [547]:
print(tf.config.list_physical_devices("GPU"))

[]


In [548]:
!nvidia-smi

Sat Aug 21 14:05:31 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 471.11       Driver Version: 471.11       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   50C    P5    14W /  N/A |    626MiB /  8192MiB |     17%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [1]:
# 1. tf.constant()로 임의의 값으로 벡터, 스칼라, 행렬 및 텐서 생성
import tensorflow as tf
scalar = tf.constant(5)
vector = tf.constant([5, 10])
matrixs = tf.constant([
    [1, 2],
    [3, 4]
])
tensor = tf.constant([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

In [5]:
# 2. 1에서 생성한 텐서의 shape, rank 및 size 
print(f'{scalar.shape} {scalar.ndim} {tf.size(scalar)}')
print(f'{vector.shape} {vector.ndim} {tf.size(vector)}')
print(f'{matrixs.shape} {matrixs.ndim} {tf.size(matrixs)}')
print(f'{tensor.shape} {tensor.ndim} {tf.size(tensor)}')

() 0 1
(2,) 1 2
(2, 2) 2 4
(2, 2, 2) 3 8


In [7]:
# 3. shape가 [5, 300]인 0과 1 사이의 임의 값을 포함하는 두개 텐서 만들기
import numpy as np
X = tf.constant(np.random.randint(0, 1, 1500), shape=(5, 300))
Y = tf.constant(np.random.randint(0, 1, 1500), shape=(5, 300))
X, Y

(<tf.Tensor: shape=(5, 300), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])>,
 <tf.Tensor: shape=(5, 300), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])>)

In [9]:
# 4. 행렬 곱으로 3에서 만든 두 텐서 곱하기
X @ tf.reshape(Y, shape=(300, 5))

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [10]:
# 5. 내적으로 3에서 만든 두 텐서를 곱한다
tf.tensordot(X, tf.transpose(Y), axes = 1)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [12]:
# 6. shape가 [224, 224, 3]인 0과 100사이의 임의 값 텐서 만들기
tensor = tf.constant(np.random.randint(0, 100, 150528), shape=(224, 224, 3))

In [14]:
# 7. 6의 텐서의 최소, 최대값
tf.reduce_max(tensor), tf.reduce_min(tensor)
tf.argmax(tensor), tf.argmin(tensor)

(<tf.Tensor: shape=(224, 3), dtype=int64, numpy=
 array([[ 36,  56,  26],
        [ 23, 126,  28],
        [ 21, 127, 155],
        [ 31,  11,  38],
        [ 36,  92,  55],
        [  7, 113,  16],
        [  2,  81, 163],
        [ 10,  55,  77],
        [ 94,   1,  38],
        [ 15,  97,  15],
        [ 53,  88,  90],
        [ 62,   9, 172],
        [137, 178, 136],
        [ 70,  95, 122],
        [ 97,  34,  53],
        [  4, 129,  38],
        [ 73, 144,  64],
        [137,  40, 189],
        [ 45,  15,  18],
        [210,  15,   5],
        [  0, 173,  36],
        [ 25,  15,  59],
        [  3,   7,  78],
        [126, 165, 122],
        [141, 191,  38],
        [136, 112, 168],
        [ 62, 127,   0],
        [ 25,  93,  21],
        [165,  45,  16],
        [102, 121,  36],
        [ 31,   7,  55],
        [ 35, 213,  93],
        [ 69,  55, 127],
        [  4,  52,  65],
        [  6,  65,  12],
        [ 54, 194,  78],
        [ 68,  62,  43],
        [184,  32, 148],
 

In [15]:
# 8. [1, 224, 224, 3] 모양의 임의 값으로 텐서 만들고 모양을 [224, 224, 3]으로 변경
my_tensor = tf.constant(np.random.randint(0, 200000, 150528), shape=(1, 224, 224, 3))
mytensor = tf.squeeze(my_tensor)


In [17]:
# 9. shape가 10인 텐서를 만들고 최대값인 인덱스
tensor = tf.constant(np.random.randint(0, 100, 10))
tf.argmax(tensor).numpy()

8

In [20]:
# 9에서 생성한 텐서를 웟-핫 인코딩
tf.one_hot(tensor, depth=100)

<tf.Tensor: shape=(10, 100), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.,