In [ ]:
## 003_Autograd.ipynb

In [9]:
import torch

In [10]:
x = torch.tensor([-1.2365, 1.8245, -1.0701, 0.0869, -0.0376])

In [11]:
x, type(x)

(tensor([-1.2365,  1.8245, -1.0701,  0.0869, -0.0376]), torch.Tensor)

In [12]:
loss = x**2 - 5

In [13]:
loss

tensor([-3.4711, -1.6712, -3.8549, -4.9924, -4.9986])

In [14]:
x = torch.tensor([-1.2365, 1.8245, -1.0701, 0.0869, -0.0376], requires_grad = True)

In [15]:
x, type(x)

(tensor([-1.2365,  1.8245, -1.0701,  0.0869, -0.0376], requires_grad=True),
 torch.Tensor)

In [16]:
loss = x**2 - 5

In [17]:
loss

tensor([-3.4711, -1.6712, -3.8549, -4.9924, -4.9986], grad_fn=<SubBackward0>)

In [18]:
loss.grad_fn

In [20]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

In [21]:
loss.backward(gradient=torch.ones(5))

In [22]:
x.grad

tensor([-2.4730,  3.6490, -2.1402,  0.1738, -0.0752])

In [24]:
x

tensor([-1.2365,  1.8245, -1.0701,  0.0869, -0.0376], requires_grad=True)

In [35]:
y = torch.Tensor([4., 9., 16., 25.])

In [36]:
y.grad

In [37]:
y = torch.tensor([4., 9., 16., 25.], requires_grad = True)

In [38]:
y.grad

In [ ]:
$$\frac{\partial y}{\partial x} = 2x$$

$$\frac{\partial y}{\partial x} = 2x$$

In [39]:
2 * x

tensor([-2.4730,  3.6490, -2.1402,  0.1738, -0.0752], grad_fn=<MulBackward0>)

In [40]:
a = torch.rand(2, 2, requires_grad=True)

In [41]:
a

tensor([[0.2321, 0.4556],
        [0.6082, 0.2334]], requires_grad=True)

In [42]:
a.requires_grad

True

In [43]:
b = a.detach()

In [44]:
b.requires_grad

False

In [51]:
c = torch.rand(2, 2, requires_grad=True)
c

tensor([[0.4757, 0.8250],
        [0.6379, 0.5900]], requires_grad=True)

In [52]:
with torch.no_grad():
    loss = c ** 2
    print(loss)
    print(loss.requires_grad)

tensor([[0.2263, 0.6807],
        [0.4069, 0.3481]])
False
