# 00_tensorflow_fundamentals.ipynb

In [17]:
import tensorflow as tf

print(tf.__version__)

2.6.0


## tensorflow : 데이터 전처리, 데이터 모델링, 모델 제공을 위한 오픈소스 머신 러닝 라이브러리



In [18]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [19]:
scalar.ndim

0

In [20]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [21]:
vector.ndim # ndim은 number of dimensions

1

## 일반적으로 tensorflow를 사용할 때 위에서처럼 직접 텐서를 만들지 않습니다. 
## Tensorflow에 내장된 모듈인 tf.io나 tf.data 가 데이터를 읽고 쓸 때 자동으로 데이터를
## 텐서로 변환한 다음 나중에 신경망 모델에 적용 및 처리합니다.

## scalar (스칼라)는 rank가 0인 tensor! 왜냐하면 ndim이 0이라서 그렇습니다.
## tensor는 dimension에 제한이 없다는 것이 중요합니다!

In [22]:
matrix = tf.constant(
    [
        [10, 7],
        [7, 10]
    ]
)
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [23]:
matrix.ndim

2

In [24]:
matrix2 = tf.constant(
    [
        [10., 7.],
        [7., 10.]
    ]
)
matrix2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 7., 10.]], dtype=float32)>

## tensorflow는 기본적으로 tensor를 생성할 때, 자료형 (Datatype)을 int32나 float32로 설정합니다.

In [25]:
another_matrix = tf.constant(
    [
        [10., 7.],
        [3., 2.],
        [8., 9.]
    ],
    dtype = tf.float16
)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [26]:
another_matrix.ndim

2

In [27]:
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [28]:
tensor.ndim  # 2행 3열짜리 행렬이 3개가 있다! 
# rank가 3인 tensor!

3

## 위에서 굳이 scalar, vector, matrix, tensor 등등으로 구분해서 표현을 했지만
## 기술적으로는 사실 위의 모든 것이 tensor입니다.

In [29]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [31]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [ ]:
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## tf.constant()을 사용해야 할지... tf.Variable()을 사용해야 할지...
## 우리가 해결할 문제에 따라서 선택하면 되고, 
## 우리가 실제로 직접 tensor를 만들 경우는 없습니다. 
## 왜? tensorflow가 데이터를 불러오고, 모델링할 때 알아서 선택해 줍니다.

In [ ]:
random_1 = tf.random.Generator.from_seed(42) # np.random.seed(42)와 비슷
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

In [ ]:
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
random_3 = tf.random.Generator.from_seed(42)
random_3 = random_3.normal(shape=(3, 2))
random_4 = tf.random.Generator.from_seed(11)
random_4 = random_4.normal(shape=(3, 2))

In [ ]:
random_3, random_4, random_3 == random_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.27305737, -0.29925638],
        [-0.3652325 ,  0.61883307],
        [-1.0130816 ,  0.28291714]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

## 왜 shuffle을 해야하는지...
## 딥러닝시 이미지가 15,000개가 있을 때, 처음에 10,000은 고양이
## 그리고, 이어서 나머지 5,000은 개!
## 이 순서대로 학습을 하게 된다면 신경망에 overfit을 유발시킬 수도 있습니다.

In [ ]:
not_shuffled = tf.constant([
    [10, 7],
    [3, 4],
    [2, 5]
])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [ ]:
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [ ]:
tf.random.shuffle(tensor)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

![scalar-vector-matrix-tensor 비교](images/00-scalar-vector-matrix-tensor.png)

## (224, 224, 3, 32)
## 224, 224 (첫부분 2차원) : 픽셀 단위로 이미지의 높이 (height) 와 너비 (width)
## 3 : 이미지의 컬러 채널 (RGB, Red Green Blue)
## 32 : 배치 (Batch) 크기 -  1번에 신경망이 처리할 이미지의 갯수

In [ ]:
tf.ones(shape = (3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape = (3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32) # 24개
A = tf.constant(numpy_A, shape=[2, 4, 3]) # 24 = 2 * 4 * 3

numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])>)

In [ ]:
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

## tensor의 정보 (shape, rank, size)를 얻는 과정 
## shape : tensor를 이루는 각각의 차원의 길이 (elements의 수)
## Rank : tensor를 이루는 차원의 갯수 (scalar는 0 / vector는 1 / matrix는 2 / tensor는 n (number) )
## Axis or Dimension : tensor의 특정 차원을 지칭
## size : tensor를 이루는 items (elements의 갯수)

In [ ]:
print("모든 elements의 자료형은 ", rank_4_tensor.dtype)
print("차원의 갯수 (rank)는 ", rank_4_tensor.ndim)
print("텐서의 shape는 ", rank_4_tensor.shape)
print("텐서의 axis 0에 속하는 element들은 ", rank_4_tensor.shape[0])
print("텐서의 axis 1에 속하는 element들은 ", rank_4_tensor.shape[1])
print("텐서의 마지막 axis에 속하는 element들은 ", rank_4_tensor.shape[-1])
print("모든 element의 갯수 (2 * 3 * 4 * 5)는 ", tf.size(rank_4_tensor).numpy())
# numpy()를 사용한 이유는 tf.size가 결과를 tensor로 주기 때문에 이 tensor를 numpy array형태로 변환이 필요

모든 elements의 자료형은  <dtype: 'float32'>
차원의 갯수 (rank)는  4
텐서의 shape는  (2, 3, 4, 5)
텐서의 axis 0에 속하는 element들은  2
텐서의 axis 1에 속하는 element들은  3
텐서의 마지막 axis에 속하는 element들은  5
모든 element의 갯수 (2 * 3 * 4 * 5)는  <class 'numpy.int32'>


In [ ]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([
    [10, 7],
    [3, 4]
])

In [ ]:
# 각 행의 마지막 elements를 출력
rank_2_tensor[:, -2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  3])>

In [ ]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_2_tensor, rank_2_tensor.ndim, rank_3_tensor, rank_3_tensor.ndim
# 파이썬에서 ...는 기존에 존재하는 것은 모두 유지

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]])>,
 2,
 <tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
 array([[[10],
         [ 7]],
 
        [[ 3],
         [ 4]]])>,
 3)

In [ ]:
tf.expand_dims(rank_2_tensor, axis = -1)
# axis = -1 / 마지막 차원이라는 뜻

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [ ]:
tensor = tf.constant([
    [10, 7],
    [3, 4]
])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [ ]:
tensor = tf.Variable([
    [10, 7],
    [3, 4]
])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [ ]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [ ]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [ ]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [ ]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [ ]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [ ]:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [ ]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [ ]:
tf.subtract(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [ ]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

## TensorFlow에서는 matrix multiplication을 tf.matmul()로 처리합니다.
## 파이썬에서 @는 matrix multiplication을 의미하기도 합니다. @는 annotation을 의미하기도 합니다.
## 규칙 1 : 안에 있는 차원이 같아야 한다
## (3, 5) @ (3, 5) ==> 안 됨!
## (5, 3) @ (3, 5) ==> 잘 됨!
## (3, 5) @ (5, 3) ==> 잘 됨!

## 규칙 2: 연산의 결과 행렬은 외부 차원들로 이루어 진다
## (5, 3) @ (3, 5) => (5, 5)
## (3, 5) @ (5, 3) => (3, 3)

In [ ]:
tensor = tf.constant([
    [10, 7],
    [3, 4]
])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [ ]:
# (2, 2) @ (2, 2)
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [33]:
X = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
])

Y = tf.constant([
    [7, 8],
    [9, 10],
    [11, 12]
])
X, Y, X.ndim, Y.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>,
 2,
 2)

In [34]:
# (3, 2) @ (3, 2) => 규칙 1 위반

X @ Y

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,2] 0 0 [Op:MatMul]

In [35]:
tf.matmul(X, Y)

InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [3,2] [3,2] 0 0 [Op:MatMul]

## 위와 같은 경우를 해결하려면
## (3, 2) @ (3, 2)
## 1) X의 shape 변경 => (2, 3) @ (3, 2) => 결과 (2, 2)
## 2) Y의 shape 변경 => (3, 2) @ (2, 3) => 결과 (3, 3)

In [36]:
tf.reshape(X, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [37]:
tf.reshape(X, shape=(2, 3)) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [38]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [39]:
X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [40]:
X, tf.reshape(X, shape=(2, 3)), tf.transpose(X)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>)

In [41]:
tf.reshape(X, shape=(2, 3)) @ Y, tf.transpose(X) @ Y

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 58,  64],
        [139, 154]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]])>)

In [42]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [43]:
tf.matmul(a = X, b= Y, transpose_a = True, transpose_b = False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [44]:
tf.tensordot(tf.transpose(X), Y, axes = 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [45]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [46]:
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [47]:
Y.shape, tf.reshape(Y, (2, 3))

(TensorShape([3, 2]),
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>)

In [48]:
Y.shape, tf.reshape(Y, (2, 3)).shape, tf.transpose(Y).shape

(TensorShape([3, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [49]:
Y.shape, tf.reshape(Y, (2, 3)), tf.transpose(Y)

(TensorShape([3, 2]),
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]])>)

## tf.reshape() : 주어진 tensor의 shape를 지정한 shape로 변경. 그 값이 나온 순서대로 (행에서 그리고 열) 값을 채운다
## tf.transpose() : 축을 변경

In [50]:
B = tf.constant([1.7, 7.4])

In [51]:
C = tf.constant([1, 7])

In [52]:
B, C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 7])>)

In [54]:
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [55]:
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 7.], dtype=float32)>

In [56]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [57]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [59]:
import numpy as np
E = tf.constant(np.random.randint(low=0, high = 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 6, 50, 61, 71, 10, 34, 76, 31, 75, 20,  7, 85, 98, 69, 52, 81, 26,
       78, 74, 54, 79, 60, 95, 97, 52, 59, 69, 48, 14, 90, 29, 78, 25, 98,
       79, 88, 19, 45, 82, 36, 39, 26, 95,  7, 52, 76, 26, 37, 69, 52])>

In [60]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [61]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [62]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=55>

In [63]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2779>

In [65]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=27.4>

In [66]:
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=751.5>

In [67]:
tf.argmax(E)   # max 값의 위치를 알려준다

<tf.Tensor: shape=(), dtype=int64, numpy=12>

In [68]:
tf.argmin(E)   # min 값의 위치를 알려준다

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [69]:
G = tf.constant(np.random.randint(0, 100, 50), shape = (1, 1, 1, 1, 50))
G, G.shape, G.ndim

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int32, numpy=
 array([[[[[84, 32, 99, 71, 53, 82, 67, 57, 40, 11, 73, 67,  7, 35, 31,
            37, 55, 82, 10, 53, 45, 62, 96, 88, 48, 80, 20, 88, 54, 54,
            55, 19, 85, 97, 35, 84, 72, 10, 82, 29, 85, 93, 84, 30, 90,
            53, 83, 95, 72, 29]]]]])>,
 TensorShape([1, 1, 1, 1, 50]),
 5)

In [70]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed.ndim

(TensorShape([50]), 1)

In [72]:
G_sqeezed = tf.squeeze(G)
G_sqeezed.shape, G_sqeezed.ndim

# 차원의 크기가 1인 차원을 제거해 주는 함수

(TensorShape([50]), 1)

In [73]:
some_list = [0, 1, 2, 3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [74]:
tf.one_hot(some_list, depth=4, on_value='On', off_value='Off')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'On', b'Off', b'Off', b'Off'],
       [b'Off', b'On', b'Off', b'Off'],
       [b'Off', b'Off', b'On', b'Off'],
       [b'Off', b'Off', b'Off', b'On']], dtype=object)>

In [75]:
H = tf.constant(np.arange(1, 10))
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [76]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [77]:
H = tf.cast(H, dtype=tf.float16)
H.dtype, H

(tf.float16,
 <tf.Tensor: shape=(9,), dtype=float16, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float16)>)

In [79]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [80]:
H = tf.cast(H, dtype=tf.float32)
H.dtype, H

(tf.float32,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)>)

In [81]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [82]:
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([0, 1, 2, 3, 4])>

In [83]:
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([ 0,  1,  2,  3, 50])>

In [85]:
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int32, numpy=array([10, 11, 12, 13, 60])>

In [86]:
# Numpy array로 tensor 생성
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [87]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [88]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [89]:
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
numpy_J, tensor_J

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 3.,  7., 10.], dtype=float32)>)

In [90]:
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [92]:
def function(x, y):
    return x ** 2 + y

x = tf.constant(np.arange(0, 10))
y = tf.constant(np.arange(10, 20))
function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [94]:
@tf.function    # decorator
def tf_function(x, y):
    return x ** 2 + y

tf_function(x, y)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 10,  12,  16,  22,  30,  40,  52,  66,  82, 100])>

In [96]:
print(tf.config.list_physical_devices('GPU'))

[]
